/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import controllers.CustomerService;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class DepositFrame extends javax.swing.JFrame {

    /**
     * Creates new form DepositFrame
     */
    
    CustomerService customerService;
    
    public DepositFrame(CustomerService customerService) {
        this.customerService = customerService;
        initComponents();
    }
    
    public DepositFrame() {
        initComponents();
    }

    public JTextField getDepositTxtField() {
        return depositTxtField;
    }

    public void setDepositTxtField(JTextField depositTxtField) {
        this.depositTxtField = depositTxtField;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depositTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        depositBtn = new javax.swing.JButton();

        setResizable(false);

        depositTxtField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        depositTxtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        depositTxtField.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("VNĐ");

        depositBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        depositBtn.setText("Deposit");
        depositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(depositTxtField)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(depositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(depositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBtnActionPerformed
        // TODO add your handling code here:
        customerService.depositBtn();
    }//GEN-LAST:event_depositBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton depositBtn;
    private javax.swing.JTextField depositTxtField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
